// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKucoiEhbkzkbw-MqYfflkoKSo8XGV-Ac',
    appId: '1:701842227761:web:f6dbc3451151dec0b50b10',
    messagingSenderId: '701842227761',
    projectId: 'mustaphaabdulrahman0',
    authDomain: 'mustaphaabdulrahman0.firebaseapp.com',
    storageBucket: 'mustaphaabdulrahman0.firebasestorage.app',
    measurementId: 'G-DQJSKSB1DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVMx0bnQnbKLEFvRyZ1zpDI3b62Q0xNHY',
    appId: '1:701842227761:android:83417c52229a1edeb50b10',
    messagingSenderId: '701842227761',
    projectId: 'mustaphaabdulrahman0',
    storageBucket: 'mustaphaabdulrahman0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYxPNiVwLoizz-MO82nkoUGSVQd-35bDg',
    appId: '1:701842227761:ios:2d3e442ce34d4511b50b10',
    messagingSenderId: '701842227761',
    projectId: 'mustaphaabdulrahman0',
    storageBucket: 'mustaphaabdulrahman0.firebasestorage.app',
    iosBundleId: 'com.mustaphaprojects.mustaphaprojects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYxPNiVwLoizz-MO82nkoUGSVQd-35bDg',
    appId: '1:701842227761:ios:2d3e442ce34d4511b50b10',
    messagingSenderId: '701842227761',
    projectId: 'mustaphaabdulrahman0',
    storageBucket: 'mustaphaabdulrahman0.firebasestorage.app',
    iosBundleId: 'com.mustaphaprojects.mustaphaprojects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKucoiEhbkzkbw-MqYfflkoKSo8XGV-Ac',
    appId: '1:701842227761:web:233adeb3734e66cdb50b10',
    messagingSenderId: '701842227761',
    projectId: 'mustaphaabdulrahman0',
    authDomain: 'mustaphaabdulrahman0.firebaseapp.com',
    storageBucket: 'mustaphaabdulrahman0.firebasestorage.app',
    measurementId: 'G-7ES4EFEV30',
  );
}
